services:

  doorman-admin:
    image: airenas/api-doorman-admin:dev
    #   - "${ADMIN_PORT}:8000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_DSN: "postgres://postgres:postgres@postgres:5432/doorman?sslmode=disable"
      PROJECTS: test,tts,changes
    restart: on-failure

  postgres:
    image:   postgres:17-alpine3.21
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=doorman
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s     
      timeout: 1s       
      retries: 5        
      start_period: 1s 

  dbmigration:
    image: airenas/api-doorman-dbmigration:dev
    command:
      [
        '-path',
        '/db/migrations',
        '-database',
        'postgres://postgres:postgres@postgres:5432/doorman?sslmode=disable',
        'up',
      ]
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy     

  integration-tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    depends_on:
      - doorman-admin
    environment:
      ADMIN_URL: http://doorman-admin:8000  
    volumes:
      - ../../../:/go/src/
    command: -tags integration -v -count=1 ./testing/integration/cms/...

  unit-tests:
    build:
      context: .
      dockerfile: ./Dockerfile.test
    volumes:
      - ../../../:/go/src/
    command: -v -count=1 ./...
