port: 8000
logger:
    level: TRACE
    out: CONSOLE
proxy:
    handlers: tts,asr,default
    tts:
        type: quota
        db: tts
        backend: http://localhost:8002
        prefixURL: /private/test
        stripPrefix: /private
        method: POST
        quota:
            type: json
            field: text
            default: 100
    asr:
        type: quota
        db: asr
        backend: http://localhost:8002
        prefixURL: /private
        method: POST
        quota:
            type: json
            field: text
            default: 100
    default:
        backend: http://localhost:8002

db:
    dsn: postgres://postgres:postgres@localhost:5432/doorman?sslmode=disable

ipExtractType: lastForwardFor
