port: 8000 
proxy:
    backend: http://list.airenas.eu:6080/
    prefixURL: /synthesis.service/synthesizer
    method: POST
    quota:
        type: json
        field: text
        default: 15

# overwrite with env variable MONGO_URL
mongo: 
    url: mongodb://xxx:xxx@localhost:27017      