port: 8000 
proxy:
    backend: http://localhost:8002
    prefixURL: /private
    method: POST
    quota:
        type: json
        field: text
        default: 100

# overwrite with env variable MONGO_URL
mongo: 
    url: mongodb://xxx:xxx@localhost:27017    

ipExtractType: lastForwardFor    