port: 8001
logger:
    level: TRACE
    out: CONSOLE

keySize: 30

projects: tts,asr,test

db:
    dsn: postgres://postgres:postgres@localhost:5432/doorman?sslmode=disable

hashSalt: ohcheiPhahBahPa2aephei6eiree5P
mainAdmin: 
    key: olia
    maxLimit: 100000000
    forceShortKey: true
ipExtractType: lastForwardFor   
