version: '3.7'

services:
  doorman:
    image: airenas/api-doorman:${DOORMAN_VERSION}
    ports:
      - "${DOORMAN_PORT}:8000"
    environment:
      MONGO_URL: "${MONGO_URL}"  
      PROXY_HANDLERS: "test,test2,test3,default"
      PROXY_DEFAULT_BACKEND: "http://test-api:8000/"
      PROXY_TEST_TYPE: quota
      PROXY_TEST_DB: test
      PROXY_TEST_BACKEND: "http://test-api:8000/"
      PROXY_TEST_PREFIXURL: "/private"
      PROXY_TEST_QUOTA_TYPE: "json"
      PROXY_TEST_QUOTA_FIELD: "text"
      PROXY_TEST_QUOTA_DEFAULT: 100
      PROXY_TEST2_TYPE: simple
      PROXY_TEST2_DB: test
      PROXY_TEST2_BACKEND: "http://test-api:8000/"
      PROXY_TEST2_PREFIXURL: "/simple/public"
      PROXY_TEST2_STRIPPREFIX: "/simple"
      PROXY_TEST2_QUOTA_DEFAULT: 100
      PROXY_TEST3_TYPE: quota
      PROXY_TEST3_DB: test
      PROXY_TEST3_BACKEND: "http://test-api:8000/"
      PROXY_TEST3_PREFIXURL: "/quotatts/private"
      PROXY_TEST3_STRIPPREFIX: "/quotatts"
      PROXY_TEST3_QUOTA_TYPE: "jsonTTS"
      PROXY_TEST3_QUOTA_DISCOUNT: 0.80
      PROXY_TEST3_QUOTA_DEFAULT: 100
    # restart: unless-stopped

  doorman-admin:
    image: airenas/api-doorman-admin:${ADMIN_VERSION}
    ports:
      - "${ADMIN_PORT}:8000"
    environment:
      MONGO_URL: "${MONGO_URL}"  
      PROJECTS: test,test1
    # restart: unless-stopped
  
  test-api:
    image: airenas/test-api:${TEST_API_VERSION}
    ports:
      - "${TEST_API_PORT}:8000"

  mongo:
    image: mongo:4.4.1
    hostname: mongo
    environment:
      MONGO_DATA_DIR: "/data/db"
      MONGO_LOG_DIR: "/dev/null"
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    ports:
      - "${MONGO_PORT}:27017"
    volumes:
      - ./.mongo:/data/db
    # restart: unless-stopped     
    command: mongod --replSet rs0 --logpath=/dev/null --bind_ip mongo,localhost 