name: Go

on:
  push:
    branches: [ main, tts]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Generate mocks
      run: make generate

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
 
    - name: Build
      run: go build -v ./...

    - name: Test
      run: make test/unit

    - name: Run vet & lint
      run: make test/lint 
        
    - name: Go report
      uses: creekorful/goreportcard-action@v1.0

    - name: Calc coverage
      run: |
        go test -v -covermode=count -coverprofile=coverage.out ./...
    - name: Convert coverage.out to coverage.lcov
      uses: jandelgado/gcov2lcov-action@v1.0.6
    - name: Coveralls
      uses: coverallsapp/github-action@v1.1.2
      with:
          github-token: ${{ secrets.github_token }}
          path-to-lcov: coverage.lcov    
  