name: Integration Tests
on:
  push:
    branches: [ main, tts ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: make build/doorman-admin
      - name: Run integration tests
        run: make test/integration
