name: Integration Tests
on:
  push:
    branches: [ main, tts ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: actions/checkout@v2
      - name: Build container
        run: make build/doorman-admin
      - name: Run integration tests
        run: make test/integration
