name: Integration Tests
on:
  push:
    branches: [ main, tts ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: make docker/doorman-admin/build docker/doorman/build
      - name: Run integration tests
        run: make test/integration

