name: Load Tests
on:
  push:
    branches: [ main, tts ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build containers
        run: make build/doorman-admin build/doorman
      - name: Run load tests
        run: make test/load
