name: Load Tests
on:
  push:
    branches: [ main, tts, to-postgresql ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: 1.19
      - uses: actions/checkout@v2
      - name: Build containers
        run: make docker/doorman-admin/build docker/doorman/build
      - name: Run load tests
        run: make test/load
